export interface CalculatorSearchItem {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: string;
  keywords: string[];
  synonyms: string[];
  status: 'mock' | 'draft' | 'published';
  isPremium: boolean;
  estimatedMinutes?: number;
}

export const MOCK_CALCULATORS_INDEX: CalculatorSearchItem[] = [
  {
    id: 'GOV-001',
    slug: 'fhdyo-tugilganlik-guvohnomasi',
    title: 'Tug‘ilganlik guvohnomasi',
    description: 'Tug‘ilganlik guvohnomasi bilan bog‘liq to‘lovlarni holatingizga qarab hisoblang.',
    category: 'hujjatlar',
    keywords: ['tug‘ilganlik', 'guvohnoma', 'metrika', 'bolalar', 'fhdyo', 'dublikat'],
    synonyms: ['metrka olish', 'tugilganlik guvohnoma', 'chaqaloqqa guvohnoma'],
    status: 'mock',
    isPremium: false,
    estimatedMinutes: 2,
  },
  {
    id: 'CRT-001',
    slug: 'sud-boji-hisoblash',
    title: 'Sud boji hisoblash (Mulk va nomulkiy da’volar)',
    description: 'Fuqarolik va iqtisodiy sudlarga da’vo arizasi topshirishda to‘lanadigan davlat boji.',
    category: 'sud',
    keywords: ['sud', 'sud boji', 'da’vo', 'ariza', 'sudya', 'iqtisodiy sud', 'fuqarolik sudi'],
    synonyms: ['sudga to‘lov', 'sud xarajati', 'davo arizasi boji'],
    status: 'mock',
    isPremium: false,
    estimatedMinutes: 3,
  },
  {
    id: 'NOT-002',
    slug: 'avtomobil-ishonchnomasi-notarius',
    title: 'Avtomobil ishonchnomasi notarial to‘lovi',
    description: 'Avtotransport vositasini boshqarish yoki tasarruf etish ishonchnomasini tasdiqlash xarajatlari.',
    category: 'notarius',
    keywords: ['avtomobil', 'mashina', 'ishonchnoma', 'doverennost', 'notarius', 'tasarruf'],
    synonyms: ['doverennost olish', 'mashinaga doverennost', 'notarius ishonchnoma'],
    status: 'mock',
    isPremium: false,
    estimatedMinutes: 2,
  },
  {
    id: 'CAD-008',
    slug: 'uy-sotish-xarajatlari',
    title: 'Uy sotish xarajatlari va notarial bojlari',
    description: 'Kvartira yoki yakka tartibdagi uyni oldi-sotdi shartnomasini rasmiylashtirish va davlat boji.',
    category: 'uy-joy',
    keywords: ['uy', 'kvartira', 'xonadon', 'sotish', 'ko‘chmas mulk', 'oldi-sotdi', 'notarius'],
    synonyms: ['kvartira sotish', 'uyimni sotish', 'uy oldi sotdisi'],
    status: 'mock',
    isPremium: true,
    estimatedMinutes: 4,
  },
  {
    id: 'AUT-003',
    slug: 'avtomobil-davlat-raqami-va-royxat',
    title: 'Avtomobilni DYHXXda ro‘yxatdan o‘tkazish to‘lovlari',
    description: 'Yangi yoki ikkilamchi avtomashinani ro‘yxatga olish, davlat raqami va texnik pasport xarajatlari.',
    category: 'avtomobil',
    keywords: ['avto', 'mashina', 'nomer', 'davlat raqami', 'texpasport', 'dyhxx', 'gai'],
    synonyms: ['mashina nomer olish', 'gai da royxat', 'texpasport olish'],
    status: 'mock',
    isPremium: false,
    estimatedMinutes: 3,
  },
  {
    id: 'TAX-004',
    slug: 'jismoniy-shaxslar-daromad-soligi',
    title: 'Jismoniy shaxslar daromad solig‘i (JShODS)',
    description: 'Mehnat shartnomasi va fuqarolik-huquqiy shartnomalar bo‘yicha oylik daromad solig‘ini hisoblash.',
    category: 'soliq',
    keywords: ['soliq', 'daromad', 'jshods', 'oylik', 'maosh', 'ndfl', 'soliq stavkasi'],
    synonyms: ['oylikdan soliq', 'daromad soligi hisoblash', 'maosh soligi'],
    status: 'mock',
    isPremium: false,
    estimatedMinutes: 2,
  },
  {
    id: 'CST-005',
    slug: 'mashina-olib-kirish-bojxona',
    title: 'Avtomobil olib kirishdagi bojxona to‘lovlari',
    description: 'Xorijdan yengil avtomobil import qilishda to‘lanadigan bojxona boji, QQS va utilizatsiya yig‘imi.',
    category: 'bojxona',
    keywords: ['bojxona', 'rastamojka', 'mashina', 'import', 'avtomobil', 'utilizatsiya', 'qqs'],
    synonyms: ['avto rastamojka', 'mashina olib kirish', 'chet eldan mashina'],
    status: 'mock',
    isPremium: true,
    estimatedMinutes: 5,
  },
  {
    id: 'DOC-006',
    slug: 'xorijga-chiqish-pasporti',
    title: 'Xorijga chiqish biometrik pasporti (Zagranpasport)',
    description: 'Fuqarolarga xorijga chiqish biometrik pasportini berish uchun undiriladigan davlat boji.',
    category: 'hujjatlar',
    keywords: ['zagranpasport', 'qizil pasport', 'xorijga chiqish', 'davlat boji', 'pasport'],
    synonyms: ['zagran pasport narxi', 'qizil pasport olish', 'xorij pasporti'],
    status: 'mock',
    isPremium: false,
    estimatedMinutes: 2,
  },
  {
    id: 'BIZ-007',
    slug: 'yakka-tartibdagi-tadbirkor-royxat',
    title: 'YTT va MChJni davlat ro‘yxatidan o‘tkazish',
    description: 'Yakka tartibdagi tadbirkor yoki mas’uliyati cheklangan jamiyat tuzish bo‘yicha davlat boji.',
    category: 'biznes',
    keywords: ['ytt', 'mchj', 'biznes', 'firma ochish', 'davlat xizmatlari', 'ro‘yxatdan o‘tish'],
    synonyms: ['firma ochish to‘lovi', 'tadbirkorlik ro‘yxati', 'mchj ochish'],
    status: 'mock',
    isPremium: false,
    estimatedMinutes: 3,
  },
  {
    id: 'UTL-009',
    slug: 'elektr-energiyasi-ijtimoiy-norma',
    title: 'Elektr energiyasi bazaviy iste’mol me’yori to‘lovi',
    description: 'Aholi uchun ijtimoiy norma doirasidagi va undan yuqori iste’mol uchun oylik to‘lov.',
    category: 'kommunal',
    keywords: ['elektr', 'svet', 'tok', 'ijtimoiy norma', 'kommunal', 'hisoblagich'],
    synonyms: ['svet to‘lovi', 'tok narxi', 'elektr hisoblash'],
    status: 'mock',
    isPremium: false,
    estimatedMinutes: 2,
  },
];
