import { Injectable } from '@nestjs/common';
import { Category } from '@govcalc/types';

@Injectable()
export class CategoriesService {
  private readonly categories: Category[] = [
    {
      id: 'cat-1',
      slug: 'davlat-bojlari',
      nameUz: 'Davlat bojlari',
      nameRu: 'Госпошлины',
      nameEn: 'State Duties',
      descriptionUz: 'Davlat organlari va fuqarolik holati dalolatnomalari uchun rasmiy yig‘imlar',
      icon: 'Landmark',
      sortOrder: 1,
      calculatorCount: 1,
    },
    {
      id: 'cat-2',
      slug: 'sud',
      nameUz: 'Sud',
      nameRu: 'Суд',
      nameEn: 'Court',
      descriptionUz: 'Fuqarolik, iqtisodiy va ma’muriy sudlarga da’vo arizalari bojlari',
      icon: 'Scale',
      sortOrder: 2,
      calculatorCount: 0,
    },
    {
      id: 'cat-3',
      slug: 'notarius',
      nameUz: 'Notarius',
      nameRu: 'Нотариат',
      nameEn: 'Notary',
      descriptionUz: 'Oldi-sotdi, hadya, ishonchnoma va meros shartnomalari to‘lovlari',
      icon: 'FileCheck',
      sortOrder: 3,
      calculatorCount: 0,
    },
    {
      id: 'cat-4',
      slug: 'avtomobil',
      nameUz: 'Avtomobil',
      nameRu: 'Автомобиль',
      nameEn: 'Vehicle',
      descriptionUz: 'Avtotransportni ro‘yxatga olish, davlat raqami va texnik ko‘rik to‘lovlari',
      icon: 'Car',
      sortOrder: 4,
      calculatorCount: 0,
    },
    {
      id: 'cat-5',
      slug: 'soliq',
      nameUz: 'Soliq',
      nameRu: 'Налоги',
      nameEn: 'Taxes',
      descriptionUz: 'Jismoniy va yuridik shaxslar uchun daromad, mulk va aylanma soliqlari',
      icon: 'Receipt',
      sortOrder: 5,
      calculatorCount: 0,
    },
    {
      id: 'cat-6',
      slug: 'bojxona',
      nameUz: 'Bojxona',
      nameRu: 'Таможня',
      nameEn: 'Customs',
      descriptionUz: 'Tovarlarni olib kirish (import) boji, aksiz va bojxona rasmiylashtiruvi',
      icon: 'ShieldCheck',
      sortOrder: 6,
      calculatorCount: 0,
    },
    {
      id: 'cat-7',
      slug: 'kadastr',
      nameUz: 'Kadastr',
      nameRu: 'Кадастр',
      nameEn: 'Cadastre',
      descriptionUz: 'Mulkka kadastr pasportini tayyorlash va huquqlarni ro‘yxatdan o‘tkazish',
      icon: 'Home',
      sortOrder: 7,
      calculatorCount: 0,
    },
    {
      id: 'cat-8',
      slug: 'kommunal',
      nameUz: 'Kommunal',
      nameRu: 'Коммунальные услуги',
      nameEn: 'Utilities',
      descriptionUz: 'Elektr energiyasi, tabiiy gaz, issiq va sovuq suv tariflari hisobi',
      icon: 'Zap',
      sortOrder: 8,
      calculatorCount: 0,
    },
    {
      id: 'cat-9',
      slug: 'migratsiya',
      nameUz: 'Migratsiya',
      nameRu: 'Миграция',
      nameEn: 'Migration',
      descriptionUz: 'Xorijga chiqish pasporti, propiska va fuqarolik masalalari to‘lovlari',
      icon: 'Globe',
      sortOrder: 9,
      calculatorCount: 0,
    },
    {
      id: 'cat-10',
      slug: 'hujjatlar',
      nameUz: 'Hujjatlar',
      nameRu: 'Документы',
      nameEn: 'Documents',
      descriptionUz: 'ID-karta, haydovchilik guvohnomasi va arxiv ma’lumotnomalari',
      icon: 'FileText',
      sortOrder: 10,
      calculatorCount: 0,
    },
    {
      id: 'cat-11',
      slug: 'biznes',
      nameUz: 'Biznes',
      nameRu: 'Бизнес',
      nameEn: 'Business',
      descriptionUz: 'MChJ, YaTT va korxonalarni davlat ro‘yxatidan o‘tkazish xarajatlari',
      icon: 'Briefcase',
      sortOrder: 11,
      calculatorCount: 0,
    },
    {
      id: 'cat-12',
      slug: 'talim',
      nameUz: 'Ta’lim',
      nameRu: 'Образование',
      nameEn: 'Education',
      descriptionUz: 'Oliy ta’lim kontrakt to‘lovlari, test va malaka sertifikati yig‘imlari',
      icon: 'GraduationCap',
      sortOrder: 12,
      calculatorCount: 0,
    },
    {
      id: 'cat-13',
      slug: 'litsenziya-va-ruxsatlar',
      nameUz: 'Litsenziya va ruxsatlar',
      nameRu: 'Лицензии и разрешения',
      nameEn: 'Licenses & Permits',
      descriptionUz: 'Faoliyat turlarini litsenziyalash va ruxsat beruvchi hujjatlar bojlari',
      icon: 'Award',
      sortOrder: 13,
      calculatorCount: 0,
    },
    {
      id: 'cat-14',
      slug: 'patent-va-intellektual-mulk',
      nameUz: 'Patent va intellektual mulk',
      nameRu: 'Патенты и интелл. собственность',
      nameEn: 'Patents & IP',
      descriptionUz: 'Savdo belgisi (brend), ixtiro va sanoat namunasini patentlash to‘lovlari',
      icon: 'Lightbulb',
      sortOrder: 14,
      calculatorCount: 0,
    },
    {
      id: 'cat-15',
      slug: 'universal-kalkulyatorlar',
      nameUz: 'Universal kalkulyatorlar',
      nameRu: 'Универсальные калькуляторы',
      nameEn: 'Universal Calculators',
      descriptionUz: 'BHM hisoblagich, penya, foizlar va qarz majburiyatlari hisobi',
      icon: 'Calculator',
      sortOrder: 15,
      calculatorCount: 0,
    },
  ];

  findAll(): Category[] {
    return this.categories;
  }

  findBySlug(slug: string): Category | undefined {
    return this.categories.find((c) => c.slug === slug);
  }
}
