import Link from 'next/link';
import { PlayCircle, ArrowRight } from 'lucide-react';
import { pitch } from '@/lib/pitch';

export const metadata = { title: 'Demo — GovMind / Hisobchi', description: 'Hisobchi prototipi: demo-video, namoyish tavsifi va hisoblashni sinash havolasi.', alternates: { canonical: '/demo' } };

export default function DemoPage() {
  const directVideo = pitch.videoUrl && /\.(mp4|webm)(\?|$)/i.test(pitch.videoUrl);
  return <div className="max-w-5xl mx-auto px-5 py-12 sm:py-16 space-y-10">
    <div><Link href="/pitch" className="text-sm text-brand-500 hover:text-brand-900">← GovMind taqdimoti</Link><p className="text-emerald-700 font-semibold text-sm mt-8">Pitch Day 3.0 / Demo</p><h1 className="text-3xl sm:text-5xl font-bold mt-3">Katta platformaning birinchi moduli.</h1><p className="text-lg text-brand-600 mt-5 max-w-3xl">Hisobchi davlat xizmatlari narxini topish, holatga mos hisoblash va huquqiy asosini ko‘rish uchun yaratilmoqda. Hozir tug‘ilganlik guvohnomasi moduli orqali shu yondashuvni sinab ko‘ring. Rejadagi 45+ kalkulyator bosqichma-bosqich qo‘shiladi.</p></div>
    <section aria-labelledby="video-title" className="rounded-3xl overflow-hidden border border-brand-200"><h2 id="video-title" className="sr-only">Demo-video</h2>{directVideo ? <video controls preload="metadata" className="w-full bg-brand-950" aria-label="Hisobchi demo-videosi"><source src={pitch.videoUrl} /><a href={pitch.videoUrl}>Videoni ochish</a></video> : <div className="min-h-64 sm:min-h-80 bg-brand-950 text-white flex flex-col items-center justify-center p-8 text-center"><PlayCircle size={48} className="text-emerald-300" /><h3 className="text-2xl font-bold mt-5">{pitch.videoUrl ? 'Hisobchi demo-videosi' : 'Demo-video hali joylanmagan'}</h3><p className="text-brand-300 text-sm max-w-md mt-3">{pitch.videoUrl ? 'Videoni tashqi sahifada tomosha qilishingiz mumkin.' : 'Namoyish videosi tayyorlanmoqda. Ishlayotgan prototipni quyidagi havola orqali sinash mumkin.'}</p>{pitch.videoUrl && <a href={pitch.videoUrl} target="_blank" rel="noopener noreferrer" className="mt-6 bg-emerald-300 text-brand-950 font-semibold px-5 py-3 rounded-xl">Videoni tomosha qilish ↗</a>}</div>}</section>
    <section><h2 className="text-2xl font-bold">Demo tavsifi</h2><p className="mt-4 text-brand-600 leading-relaxed">Namoyishda guvohnoma bilan bog‘liq vaziyat va murojaat usuli tanlanadi. Hisobchi to‘lov qismlarini alohida ko‘rsatadi, hisoblash formulasini ochadi va manba havolalarini beradi. So‘ng natijani saqlash, nusxalash va chop etish imkoniyatlari ko‘rsatiladi. Video uchun rejalashtirilgan davomiylik — taxminan 3 daqiqa.</p><ol className="grid sm:grid-cols-3 gap-4 mt-6">{[['01', 'Vaziyatni tanlang', 'Birinchi yoki takroriy guvohnoma, onlayn yoki FHDYO orqali murojaat.'], ['02', 'Tarkibni ko‘ring', 'Davlat boji, gerb yig‘imi, xizmat haqi va manbalar.'], ['03', 'Natijadan foydalaning', 'Hisobni saqlang, ulashing yoki chop eting.']].map(([n, title, text]) => <li key={n} className="bg-brand-50 rounded-2xl border border-brand-200 p-5"><span className="text-emerald-700 text-sm font-mono">{n}</span><h3 className="font-bold mt-3">{title}</h3><p className="text-sm text-brand-600 mt-2">{text}</p></li>)}</ol></section>
    <section className="rounded-2xl bg-brand-900 text-white p-7"><h2 className="text-2xl font-bold">Ishlayotgan prototip</h2><p className="text-brand-300 mt-3">Ro‘yxatdan o‘tish talab qilinmaydi. Ism, pasport yoki boshqa shaxsiy ma’lumot kiritish shart emas.</p><Link href={pitch.prototype} className="inline-flex gap-2 items-center mt-6 bg-emerald-300 text-brand-950 rounded-xl px-5 py-3 font-semibold">Kalkulyatorni ochish <ArrowRight size={18} /></Link></section>
    <p className="text-sm text-brand-500">Prototip natijasi to‘lov kvitansiyasi emas. Stavkalar va imtiyozlar bo‘yicha tekshirish holatini natija bilan birga o‘qing.</p>
  </div>;
}
